version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "update"
      include: "scope"
    groups:
      dev-deps:
        dependency-type: "development"
        patterns:
          - "*"
    ignore:
      # Keep @types/node aligned with minimum supported Node.js version (20)
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
